# Generated by Django 2.2.24 on 2022-04-23 11:20

from django.db import migrations


def set_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator():
        if flat.construction_year >= 2015:
            flat.new_building = True
        elif flat.construction_year < 2015:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_field)
    ]
