# Generated by Django 2.2.24 on 2022-04-28 09:28

from django.db import migrations


def transfer_data_to_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner_deprecated,
            pure_phone_number=flat.owner_pure_phone,
            defaults={'phone_number': flat.owners_phonenumber}
        )
        owner.flats_in_ownership.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220428_0936'),
    ]

    operations = [
        migrations.RunPython(transfer_data_to_owner_model)
    ]
